import 'package:flutter/material.dart';
import 'package:qadam/src/model/color_model.dart';
import 'package:qadam/src/model/vehicle_model.dart';
import 'package:qadam/src/theme/app_theme.dart';

import '../model/location_model.dart';
import '../model/trip_model.dart';

class Defaults {
  List<VehicleModel> vehicles = [
    VehicleModel(id: 1, vehicleName: "Lacetti"),
    VehicleModel(id: 2, vehicleName: "Malibu"),
    VehicleModel(id: 3, vehicleName: "Nexia 3"),
    VehicleModel(id: 4, vehicleName: "Damas"),
    VehicleModel(id: 5, vehicleName: "Cobalt"),
    VehicleModel(id: 6, vehicleName: "Captiva"),
    VehicleModel(id: 7, vehicleName: "Spark"),
    VehicleModel(id: 8, vehicleName: "Corolla"),
    VehicleModel(id: 9, vehicleName: "Camry"),
    VehicleModel(id: 10, vehicleName: "Rav4"),
  ];

  List<ColorModel> colors = [
    ColorModel(name: "Red", colorCode: AppTheme.red),
    ColorModel(name: "Green", colorCode: AppTheme.green),
    ColorModel(name: "Blue", colorCode: AppTheme.blue),
    ColorModel(name: "Yellow", colorCode: AppTheme.yellow),
    ColorModel(name: "Purple", colorCode: AppTheme.purple),
    ColorModel(name: "Orange", colorCode: AppTheme.orange),
    ColorModel(name: "Black", colorCode: AppTheme.black),
    ColorModel(name: "White", colorCode: Colors.white),
    ColorModel(name: "Gray", colorCode: AppTheme.gray),
  ];

  List<LocationModel> locations = [
    LocationModel(id: 1, text: "Samarkand"),
    LocationModel(id: 2, text: "Samarkand city"),
    LocationModel(id: 3, text: "Urgut"),
    LocationModel(id: 4, text: "Tashkent"),
    LocationModel(id: 5, text: "Tashkent city"),
    LocationModel(id: 6, text: "Yunusobod"),
  ];

  List<TripModel> trips = [
    TripModel(
      vehicleId: 2,
      startTime: DateTime.now(),
      endTime: DateTime.now().add(const Duration(hours: 3, minutes: 30)),
      pricePerSeat: "15",
      availableSeats: 3,
    ),
    TripModel(
      vehicleId: 5,
      startTime: DateTime.now(),
      endTime: DateTime.now().add(const Duration(hours: 3, minutes: 55)),
      pricePerSeat: "12",
      availableSeats: 4,
    ),
    TripModel(
      vehicleId: 4,
      startTime: DateTime.now(),
      endTime: DateTime.now().add(const Duration(hours: 4, minutes: 25)),
      pricePerSeat: "18",
      availableSeats: 6,
    ),
    TripModel(
      vehicleId: 8,
      startTime: DateTime.now(),
      endTime: DateTime.now().add(const Duration(hours: 3, minutes: 15)),
      pricePerSeat: "23",
      availableSeats: 1,
    ),
    TripModel(
      vehicleId: 7,
      startTime: DateTime.now().add(const Duration(days: 1)),
      endTime:
          DateTime.now().add(const Duration(days: 1, hours: 4, minutes: 30)),
      pricePerSeat: "14",
      availableSeats: 2,
    ),
    TripModel(
      vehicleId: 6,
      startTime: DateTime.now(),
      endTime: DateTime.now().add(const Duration(hours: 3, minutes: 40)),
      pricePerSeat: "19",
      availableSeats: 5,
    ),
  ];

  List<LocationModel> regions = [
    LocationModel(id: 1, text: "Tashkent"),
    LocationModel(id: 2, text: "Samarkand"),
    LocationModel(id: 3, text: "Andijon"),
    LocationModel(id: 4, text: "Farg'ona"),
    LocationModel(id: 5, text: "Namangan"),
    LocationModel(id: 6, text: "Jizzax"),
    LocationModel(id: 7, text: "Sirdaryo"),
    LocationModel(id: 8, text: "Surxondaryo"),
    LocationModel(id: 9, text: "Qashqadaryo"),
    LocationModel(id: 10, text: "Buxoro"),
    LocationModel(id: 11, text: "Xorazm"),
    LocationModel(id: 12, text: "Navoiy"),
    LocationModel(id: 13, text: "Qoraqalpog'iston"),
  ];

  List<LocationModel> cities = [
    LocationModel(id: 101, text: "Tashkent City", parentID: 1),
    LocationModel(id: 102, text: "Chirchiq", parentID: 1),
    LocationModel(id: 103, text: "Angren", parentID: 1),
    LocationModel(id: 104, text: "Olmaliq", parentID: 1),
    LocationModel(id: 105, text: "Nurafshon", parentID: 1),
    LocationModel(id: 201, text: "Samarkand City", parentID: 2),
    LocationModel(id: 202, text: "Kattaqo'rg'on", parentID: 2),
    LocationModel(id: 203, text: "Urgut", parentID: 2),
    LocationModel(id: 204, text: "Bulung'ur", parentID: 2),
    LocationModel(id: 301, text: "Andijon City", parentID: 3),
    LocationModel(id: 302, text: "Asaka", parentID: 3),
    LocationModel(id: 303, text: "Shahrixon", parentID: 3),
    LocationModel(id: 304, text: "Xonobod", parentID: 3),
    LocationModel(id: 401, text: "Farg'ona City", parentID: 4),
    LocationModel(id: 402, text: "Marg'ilon", parentID: 4),
    LocationModel(id: 403, text: "Qo'qon", parentID: 4),
    LocationModel(id: 404, text: "Rishton", parentID: 4),
    LocationModel(id: 501, text: "Namangan City", parentID: 5),
    LocationModel(id: 502, text: "Chust", parentID: 5),
    LocationModel(id: 503, text: "To'raqo'rg'on", parentID: 5),
    LocationModel(id: 504, text: "Uchqo'rg'on", parentID: 5),
    LocationModel(id: 601, text: "Jizzax City", parentID: 6),
    LocationModel(id: 602, text: "G'allaorol", parentID: 6),
    LocationModel(id: 701, text: "Guliston", parentID: 7),
    LocationModel(id: 702, text: "Yangiyer", parentID: 7),
    LocationModel(id: 801, text: "Termiz", parentID: 8),
    LocationModel(id: 802, text: "Boysun", parentID: 8),
    LocationModel(id: 901, text: "Qarshi", parentID: 9),
    LocationModel(id: 902, text: "Shahrisabz", parentID: 9),
    LocationModel(id: 1001, text: "Buxoro City", parentID: 10),
    LocationModel(id: 1002, text: "Kogon", parentID: 10),
    LocationModel(id: 1101, text: "Urganch", parentID: 11),
    LocationModel(id: 1102, text: "Xiva", parentID: 11),
    LocationModel(id: 1201, text: "Navoiy City", parentID: 12),
    LocationModel(id: 1202, text: "Zarafshon", parentID: 12),
    LocationModel(id: 1301, text: "Nukus", parentID: 13),
    LocationModel(id: 1302, text: "Mo'ynoq", parentID: 13),
  ];

  List<LocationModel> neighborhoods = [
    LocationModel(id: 10101, text: "Chilanzar", parentID: 101),
    LocationModel(id: 10102, text: "Yunusobod", parentID: 101),
    LocationModel(id: 10103, text: "Mirzo Ulug'bek", parentID: 101),
    LocationModel(id: 10104, text: "Sergeli", parentID: 101),
    LocationModel(id: 10105, text: "Shayxontohur", parentID: 101),
    LocationModel(id: 10106, text: "Olmazor", parentID: 101),
    LocationModel(id: 10201, text: "Yangiobod", parentID: 102),
    LocationModel(id: 10202, text: "Qorasuv", parentID: 102),
    LocationModel(id: 10301, text: "Istiqlol", parentID: 103),
    LocationModel(id: 10302, text: "Navoiy", parentID: 103),
    LocationModel(id: 10401, text: "Yangi Hayot", parentID: 104),
    LocationModel(id: 10501, text: "Bektemir", parentID: 105),
    LocationModel(id: 20101, text: "Samarqand Darvoza", parentID: 201),
    LocationModel(id: 20102, text: "Registon", parentID: 201),
    LocationModel(id: 20103, text: "Bog'ishamol", parentID: 201),
    LocationModel(id: 20201, text: "Olmazor", parentID: 202),
    LocationModel(id: 20202, text: "Navro'z", parentID: 202),
    LocationModel(id: 20301, text: "Chorsu", parentID: 203),
    LocationModel(id: 30101, text: "Navro'z", parentID: 301),
    LocationModel(id: 30102, text: "Istiqlol", parentID: 301),
    LocationModel(id: 30201, text: "Dustlik", parentID: 302),
    LocationModel(id: 30301, text: "Yangi Shahar", parentID: 303),
    LocationModel(id: 40101, text: "Yaypan", parentID: 401),
    LocationModel(id: 40102, text: "Toshloq", parentID: 401),
    LocationModel(id: 40201, text: "Kirguli", parentID: 402),
    LocationModel(id: 40202, text: "Paxtakor", parentID: 402),
    LocationModel(id: 40301, text: "Bog'dod", parentID: 403),
    LocationModel(id: 50101, text: "O'zbekiston", parentID: 501),
    LocationModel(id: 50102, text: "Do'stlik", parentID: 501),
    LocationModel(id: 50201, text: "Guliston", parentID: 502),
    LocationModel(id: 60101, text: "Sharq", parentID: 601),
    LocationModel(id: 60102, text: "Yangi Asr", parentID: 601),
    LocationModel(id: 70101, text: "Mirzaobod", parentID: 701),
    LocationModel(id: 80101, text: "Yangi Hayot", parentID: 801),
    LocationModel(id: 90101, text: "Muborak", parentID: 901),
    LocationModel(id: 100101, text: "Oltin Vodiy", parentID: 1001),
    LocationModel(id: 100102, text: "Sharqona", parentID: 1001),
    LocationModel(id: 110101, text: "Bog'ot", parentID: 1101),
    LocationModel(id: 110201, text: "Ichan Qal'a", parentID: 1102),
    LocationModel(id: 120101, text: "Yangi Navoiy", parentID: 1201),
    LocationModel(id: 130101, text: "Amudaryo", parentID: 1301),
    LocationModel(id: 130102, text: "Kegeyli", parentID: 1301),
  ];
}
